import type { Target, Plugin, Options, Result } from "./types";
export * from "./plugin/useLoadingDelayPlugin";
export * from "./plugin/usePollingPlugin";
export * from "./plugin/useDebouncePlugin";
export * from "./plugin/useThrottlePlugin";
export * from "./plugin/useCachePlugin";
declare function useService<Data, Params extends any[]>(target: Target<Data, Params>): Result<Data, Params>;
declare function useService<Data, Params extends any[]>(target: Target<Data, Params>, options: Options<Data, Params>): Result<Data, Params>;
declare function useService<Data, Params extends any[]>(target: Target<Data, Params>, plugins: Plugin<Data, Params>[]): Result<Data, Params>;
declare function useService<Data, Params extends any[]>(target: Target<Data, Params>, options: Options<Data, Params>, plugins: Plugin<Data, Params>[]): Result<Data, Params>;
export { useService, Target as UseServiceTarget, Plugin as UseServicePlugin, Options as UseServiceOptions, Result as UseServiceResult };
